version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexu_backend_test
    networks:
      - autos
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "7433:5432"

  web:
    build: .
    volumes:
      - ./autos:/app
    ports:
      - "5000:3000"
    depends_on:
      - db
    networks:
      - autos
    tty: true
    stdin_open: true
    #command: sh #rails server -b 0.0.0.0
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: nexu_backend_test
      DATABASE_PORT: 5432


networks:
  autos:
    driver: bridge

